apiVersion: v1
kind: Service
metadata:
  name: python-webapp-service
spec:
  type: NodePort
  selector:
    app: simple-web-app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30070
